name: Backport

on:
  pull_request:
    types: [ closed ]

permissions:
  contents: write
  pull-requests: write

jobs:
  backport:
    name: Backport changes
    if: >
      github.event.pull_request.merged == true &&
      startsWith(github.event.pull_request.base.ref, 'main')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: korthout/backport-action@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Labels like backport:release/2.2 â†’ open PR to release/2.2
          label_pattern: '^backport:(release/\d+\.\d+)$'
